/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    cms_users: CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    menus: Menu;
    email_templates: EmailTemplate;
    email_settings: EmailSetting;
    cms_users: CmsUser;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    email_templates: EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    email_settings: EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    cms_users: CmsUsersSelect<false> | CmsUsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Owning platform tenant — set automatically from the request.
   */
  tenant: string;
  title: string;
  /**
   * URL path segment, e.g. "about" or "selling/guide".
   */
  slug: string;
  /**
   * Ordered page sections (FR-D-1/3) — add, remove and reorder without engineering.
   */
  sections?:
    | (
        | HeroBlock
        | RichTextBlock
        | CtaStripBlock
        | FaqBlock
        | ThreePillarBlock
        | StatsRowBlock
        | TestimonialsBlock
        | TwoColumnBlock
        | PropertyGridBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  align?: ('left' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich_text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaStripBlock".
 */
export interface CtaStripBlock {
  heading: string;
  description?: string | null;
  ctaLabel: string;
  ctaHref: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta_strip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  title?: string | null;
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreePillarBlock".
 */
export interface ThreePillarBlock {
  heading?: string | null;
  pillars: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'three_pillar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock".
 */
export interface StatsRowBlock {
  heading?: string | null;
  stats: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats_row';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  testimonials: {
    quote: string;
    author: string;
    role?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock".
 */
export interface TwoColumnBlock {
  heading?: string | null;
  columns: {
    title?: string | null;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'two_column';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PropertyGridBlock".
 */
export interface PropertyGridBlock {
  heading?: string | null;
  /**
   * Limit to sale or rent listings (leave empty for both).
   */
  saleType?: ('sale' | 'rent') | null;
  listingType?: ('residential' | 'new_home' | 'commercial' | 'business_transfer' | 'care_home' | 'land') | null;
  /**
   * How many properties to show (default 6).
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'property_grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Owning platform tenant — set automatically from the request.
   */
  tenant: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  /**
   * Owning platform tenant — set automatically from the request.
   */
  tenant: string;
  label: string;
  /**
   * Where this menu renders. One menu per location per tenant.
   */
  location: 'header' | 'footer' | 'mobile';
  /**
   * Ordered, reorderable navigation items (FR-D-7).
   */
  items?:
    | {
        label: string;
        url: string;
        target: 'same' | 'new';
        /**
         * Optional icon name (token), not an uploaded asset.
         */
        icon?: string | null;
        /**
         * Leave empty to show to everyone; set to restrict to those staff roles.
         */
        roles?:
          | (
              | 'super_admin'
              | 'branch_manager'
              | 'property_manager'
              | 'sales_agent'
              | 'lettings_agent'
              | 'content_editor'
              | 'repairs_manager'
              | 'read_only_auditor'
            )[]
          | null;
        visibility: boolean;
        children?:
          | {
              label: string;
              url: string;
              target: 'same' | 'new';
              /**
               * Optional icon name (token), not an uploaded asset.
               */
              icon?: string | null;
              /**
               * Leave empty to show to everyone; set to restrict to those staff roles.
               */
              roles?:
                | (
                    | 'super_admin'
                    | 'branch_manager'
                    | 'property_manager'
                    | 'sales_agent'
                    | 'lettings_agent'
                    | 'content_editor'
                    | 'repairs_manager'
                    | 'read_only_auditor'
                  )[]
                | null;
              visibility: boolean;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * Owning platform tenant — set automatically from the request.
   */
  tenant: string;
  /**
   * Stable identifier the sending code looks up, e.g. "welcome".
   */
  key: string;
  name: string;
  /**
   * Email subject. Supports {{variables}}.
   */
  subject: string;
  /**
   * Hidden inbox-preview text. Supports {{variables}}.
   */
  preheader?: string | null;
  /**
   * Structured email body. Supports {{variables}} in text.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The {{variables}} this template declares.
   */
  variables?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Owning platform tenant — set automatically from the request.
   */
  tenant: string;
  host: string;
  port: number;
  /**
   * Use implicit TLS on connect (port 465).
   */
  secure?: boolean | null;
  user: string;
  /**
   * SMTP password / app password. Encrypted at rest; never shown again.
   */
  pass?: string | null;
  fromAddress: string;
  replyTo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_users".
 */
export interface CmsUser {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms_users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'email_templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'email_settings';
        value: number | EmailSetting;
      } | null)
    | ({
        relationTo: 'cms_users';
        value: number | CmsUser;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms_users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms_users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        rich_text?: T | RichTextBlockSelect<T>;
        cta_strip?: T | CtaStripBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        three_pillar?: T | ThreePillarBlockSelect<T>;
        stats_row?: T | StatsRowBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        two_column?: T | TwoColumnBlockSelect<T>;
        property_grid?: T | PropertyGridBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaStripBlock_select".
 */
export interface CtaStripBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreePillarBlock_select".
 */
export interface ThreePillarBlockSelect<T extends boolean = true> {
  heading?: T;
  pillars?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock_select".
 */
export interface StatsRowBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock_select".
 */
export interface TwoColumnBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PropertyGridBlock_select".
 */
export interface PropertyGridBlockSelect<T extends boolean = true> {
  heading?: T;
  saleType?: T;
  listingType?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        icon?: T;
        roles?: T;
        visibility?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              icon?: T;
              roles?: T;
              visibility?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  name?: T;
  subject?: T;
  preheader?: T;
  body?: T;
  variables?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  tenant?: T;
  host?: T;
  port?: T;
  secure?: T;
  user?: T;
  pass?: T;
  fromAddress?: T;
  replyTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}